### ISSUE TITLE
MD Files for PORTS of APIs

### ISSUE THREAD

**Issue by akshayvr-programmer** [Axotronics/mughup#2]
Hi  Yashraj, since I'll be creating the frontend, it will be great if you could send me  an MD File the ports on which the APIs for this app are running on. It would be really helpful.

**Comment by yashrajpahwa** [comment]
Hi Akshay,

So for development the port for the api will be
- 5000

But for prod

- 80 (ie. just the domain)

Thanks please collaborate on the frontend too

**Comment by akshayvr-programmer** [comment]
Sure. I've started learning flutter.
The App will contain three main pages:
1st Page will be the login page with firebase authentication.
2nd Page will have the camera where you can scan.
2nd page will have two tabs: Camera and text: You can click a picture and paste text.
In the 3rd Page, the user will be asked to speak what he/she  wants to memorise and the algorithm processes it so on and so forth as mentioned in the project_flow.md file.

**Comment by akshayvr-programmer** [comment]
I'm Closing this issue
