### ISSUE TITLE
Design flows in figma

### ISSUE THREAD

**Issue by yashrajpahwa** [Axotronics/mughup#4]
Hi Everyone

- Please note that we will be designing all user flows in Figma which is a free prototyping tool
- For contributing kindly leave your ideas here
- We can design flows by joining a call @17 March 2021
@akshayvr-programmer  please comment

Thanks Yashraj

**Comment by akshayvr-programmer** [comment]
Hi Yash, we've not yet added collaborators in this project. If you know anyone, you are free to do so. By when exactly do you want the frontend to be completely designed? Please let me know. I'll work accordingly. I'll learn figma in sometime. I have the project template in my head already, I just have to code the UI now. The only API which I will require from your side will be the node-rake API. The rest of the APIs will be handled by google. 

Regards,
Akshay
