### ISSUE TITLE
Removal Of initialised  Blank Flutter Project

### ISSUE THREAD

**Issue by akshayvr-programmer** [Axotronics/mughup#5]
Hi Yashraj, I'd like you to kindly remove the initialised blank flutter project. I've already done that on my PC. Once the app is completely designed, I will for sure make the complete commit and pull request.

Regards,
Akshay

**Comment by akshayvr-programmer** [comment]
There is no use, just pushing the blank initialised project

**Comment by yashrajpahwa** [comment]
Will be done shortly

**Comment by yashrajpahwa** [comment]
Done @akshayvr-programmer

**Comment by akshayvr-programmer** [comment]
Thanks
